FROM rust:1-bookworm

WORKDIR /work

RUN rustup component add rustfmt clippy

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY scripts ./scripts
COPY openwrt-config ./openwrt-config
COPY openwrt-package ./openwrt-package
COPY packaging ./packaging
COPY themes ./themes
COPY Makefile README.md ./

RUN make ci
